name: Hugo Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get GitHub Actions bot details
        id: bot-details
        uses: raven-actions/bot-details@v1

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.WEBSITE_SSH_KEY }}

      - name: Configure Git
        run: |
          git config --global user.email "${{ steps.bot-details.outputs.email }}"
          git config --global user.name "${{ steps.bot-details.outputs.name }}"
          git config --global credential.helper store

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-bibtex-extra latexmk
          npm install --save-dev --save-exact prettier

      - name: Get changed .tex files
        id: changed-tex-files
        uses: tj-actions/changed-files@v45
        with:
          files: "**/*.tex"

      - name: Build if .tex files changed
        if: steps.changed-tex-files.outputs.any_changed == 'true'
        run: |
          echo "The following .tex files have changed:"
          ./build.sh

      - name: Build if .tex files unchanged
        if: steps.changed-tex-files.outputs.any_changed == 'true'
        run: |
          ./build.sh --no-tex --ci

      - name: Run build script
        run: |
          ./build.sh --ci

      - name: Publish website
        run: |
          find .
          git -C public commit -m "${{ github.event.head_commit.message }}"
          git -C public push
