name: Hugo Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get GitHub Actions bot details
        id: bot-details
        uses: raven-actions/bot-details@v1

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.WEBSITE_SSH_KEY }}

      - name: Configure Git
        run: |
          git config --local user.email "${{ steps.bot-details.outputs.email }}"
          git config --local user.name "${{ steps.bot-details.outputs.name }}"
          git config credential.helper store

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-extra
          npm install --save-dev --save-exact prettier

      - name: Run build script
        run: |
          git clone git@github.com:stvhay/stvhay.github.io.git public
          ./build.sh

      - name: Publish website
        run: |
          git -C public commit -m "${{ github.event.head_commit.message }}"
          git -C public push